### ISSUE TITLE
Memory backend doesn't support unordered bulk operations

### ISSUE THREAD

**Issue by simonmcooper** [bwaldvogel/mongo-java-server#10]
MemoryDatabase throws an exception if it tries to execute unordered bulk operations - there's a check at the top of the various command* methods like so:
 
    boolean isOrdered = Utils.isTrue(query.get("ordered"));
    if (!isOrdered)
        throw new RuntimeException("unexpected update query: " + query);

**Comment by bwaldvogel** [comment]
Thanks for reporting.
Can you confirm that 392a3ba fixes the issue in your case(s)?
