### ISSUE TITLE
mongo-java-server xml config !!

### ISSUE THREAD

**Issue by rashmidash** [bwaldvogel/mongo-java-server#103]
Hi @bwaldvogel bwaldvogel

We are trying to use the mongo-java-server instead of fongo, but we were no in Springboot and trying to place this to some xml configuration file.

Can you please share the xml config for the same. We tried configuring java-mongo-server the way we configured fongo but couldn't get it worked. Saw @jaypatel512 talking about test-mongo.xml but couldn't find the exact configuration though.

Below is the fongo configuration used. I am looking something like this for java-mongo-server

    <bean name="fongo" class="com.github.fakemongo.Fongo">
        <constructor-arg value="InMemoryMongo" />
    </bean>
    <bean id="mongo" factory-bean="fongo" factory-method="getMongo" />
    <mongo:db-factory id="mongoDbFactory" mongo-ref="mongo" />

**Comment by markbigler** [comment]
I'm not familiar with your configuration setting and don't know how your tests look like, but you can see in the documentation which beans need to be created: https://github.com/bwaldvogel/mongo-java-server#example

This results in the following (untested) XML file:
```xml
<bean id="mongoServer" class="de.bwaldvogel.mongo.MongoServer" init-method="bind" destroy-method="shutdown">
  <constructor-arg name="backend" ref="memoryBackend" />
</bean>

<bean id="mongoClient" class="com.mongodb.MongoClient" destroy-method="close">
  <constructor-arg name="addr" ref="serverAddress" />
</bean>

<bean id="memoryBackend" class="de.bwaldvogel.mongo.backend.memory.MemoryBackend" />

<bean id="serverAddress" class="com.mongodb.ServerAddress">
  <constructor-arg name="inetSocketAddress" ref="inetSocketAddress" />
</bean>

<bean id="inetSocketAddress" class="java.net.InetSocketAddress" factory-bean="mongoServer" factory-method="getLocalAddress">
</bean>
```

**Comment by rashmidash** [comment]
Thank you so much @markbigler @bwaldvogel for your help. 

The configuration worked like a gem. Big thank from me and our team.
