### ISSUE TITLE
It's possible to create duplicate indexes on collections

### ISSUE THREAD

**Issue by Gaff** [bwaldvogel/mongo-java-server#107]
Hi,

I discovered that I can add a duplicate index (with the same name) onto a collection and it behaves just fine. This is because `AbstractMongoCollection.addIndex()` doesn't check the index name.

You only see an error when you drop the database, this is because `AbstractMongoCollection.dropIndex()` calls `CollectionUtils.getSingleElement()` which will fail because it actually contains duplicates!

Not sure how best to fix, but I'd suggest `addIndex()` should check that names are unique?

**Comment by bwaldvogel** [comment]
Thanks for this good bug report and the good analysis! I’ve indeed added such a check in `addIndex()`. Could you re-test?

**Comment by Gaff** [comment]
ok looks good - thanks :)

**Comment by bwaldvogel** [comment]
I’ve just released version `1.23.0` that contains this fix.
