### ISSUE TITLE
Support for positional $ operator in Update

### ISSUE THREAD

**Issue by Maxeh** [bwaldvogel/mongo-java-server#113]
It seems that mongo-java-server does not support the positional operator $ when an update is performed. I'm trying to run the following update, but it does not work in my tests (it works when I run the actual code):

```
Query query = new Query();
query.addCriteria(Criteria.where("myArray").elemMatch(
	Criteria.where("identifier").is("theId").and("state").is("theState")));

Update update = new Update()
    .set("myArray.$.identifier", newId)
    .set("myArray.$.state", newState);

this.mongoTemplate.updateMulti(query, update, MyEntity.class);
```
The error message is:
_The positional operator did not find the match needed from the query._

Would it be possible to fix this? It would be nice, if I am able to use my already exiting test in the future ;)

**Comment by Maxeh** [comment]
It seems that the code works with the positional all $[] operator, but not with the normal $ operator. 

This works:
```
Update update = new Update()
    .set("myArray.$[].identifier", newId)
    .set("myArray.$[].state", newState);
```

I tried to investigate and find the spot in the code to fix it, unfortunately I was not successful. Any help is appreciated.

**Comment by bwaldvogel** [comment]
Ok, thanks for this hint. I’ll try to have a closer look soon

**Comment by Maxeh** [comment]
Hello @bwaldvogel, have you looked into it? Any news?

**Comment by bwaldvogel** [comment]
I tried to reproduce it but I couldn’t.
Please have a look at the test case I introduced in fa09b7b27f87e541c68afcef6890aded9cc0f5cf.
Something is different in your case.
It would be great if you could provide a minimal test case that fails with `mongo-java-server` but succeeds with a real MongoDB.

**Comment by bwaldvogel** [comment]
I’m closing this. Feel free to reopen it with detailed instructions how to reproduce.
