### ISSUE TITLE
Add support for push options

### ISSUE THREAD

**Issue by Gaff** [bwaldvogel/mongo-java-server#117]
Mongo supports a bunch of options for `$push`, specifically:
 * `$each`
 * `$sort`
 * `$slice`
 * `$position`

See: https://docs.mongodb.com/manual/reference/operator/update/push/

More generally, if it encounters a push option it doesn't understand it should either throw or ignore it. Right now it pushes them as documents :o

**Comment by Gaff** [comment]
@bwaldvogel - I did think about having a crack at this one, but I couldn't figure out how to run the javascript tests. Is there a guide anywhere?

**Comment by bwaldvogel** [comment]
Typically I write a test in `AbstractBackendTest` and execute the subclass `RealEmbeddedMongoBackendTest` first to check if the real MongoDB fits to the test expectation.

You can find an existing test for the `$push` operator in `AbstractBackendTest#testUpdatePush` for example…

**Comment by bwaldvogel** [comment]
I added support for `$push` modifiers in afbb134d76f9a886ab76d66555d993ddac0b2137.

**Comment by bwaldvogel** [comment]
The change is available in version `1.25.0`.

**Comment by Gaff** [comment]
Looks great! Many thanks!!
