### ISSUE TITLE
BinData fields don't match when queried

### ISSUE THREAD

**Issue by talaverete** [bwaldvogel/mongo-java-server#12]
When you have a document with a binary field like ` "bin" : { "$binary" : "dBZZjw==" , "$type" : 0}` queries for that document filtering by the binary field don't yield any result.

It looks like mongo-java-server is trying to compare filter and document bin fields using equals, but it turns out bin fields are represented by arrays and hence not comparable with Object.equals(..)

**Comment by bwaldvogel** [comment]
Thanks for reporting. Can you confirm that 35d2d90 fixes your issue?

**Comment by talaverete** [comment]
It's working now, thank you!
