### ISSUE TITLE
Support $project exclusion of nested fields.

### ISSUE THREAD

**Issue by Gaff** [bwaldvogel/mongo-java-server#121]
If I have a document like so:

```
{
  "foo":  { "bar" :1, "bas": 1}
}
```

and I do: `$project("foo.bas":0)`

I should get back:

```
{
   "foo": {"bar":1}
}
```

This isn't working because `Projection.projectDoucment()` in the `if(onlyExclusions(...)){...}` clause takes a simplistic view on how to remove fields.

There's plenty of code in the same class for handling nested fields - maybe it can be changed to work with exclusions as well as inclusions?

**Comment by bwaldvogel** [comment]
I’ve reworked the `$project` staging handling to support exclusion/inclusion of nested fields.
Could you give 209a4b15587bb45aa0bf4331fab9e5d565ffdb09 a try?

**Comment by bwaldvogel** [comment]
The change is part of `v1.26.0`.

**Comment by Gaff** [comment]
HI thanks - finally got back on this. I see it works for aggregations, but not for a vanilla project. I'll raise a separate ticket.

(Also since I'm here, is it worth testing this on arrays:

```
{
  "foo": [{"a":1}, {"b:1}]
}
```
and I do: $project("foo.b":0)

I should get back:

```
{
   "foo": [{"a":1}]
}
```
)
