### ISSUE TITLE
Spring data 2.2.6 support

### ISSUE THREAD

**Issue by bsvenkat22** [bwaldvogel/mongo-java-server#127]
Hi,

MongoClient has been updated in Spring data 2.2.6 version. So the below code doesn't work. Is there any alternate for this? Or please let me know if mongo-java-server wont work with new spring boot version.

MongoClient(new ServerAddress(mongoServer().getLocalAddress()))
2.2.6 - MongoClients.create(mongoURI); - recommended way

Thanks.

**Comment by markbigler** [comment]
Thanks for the hint. I'm going to update the documentation:

```java
public class MongoTestServerConfiguration {
	@Bean
	public MongoTemplate mongoTemplate(MongoClient mongoClient) {
		return new MongoTemplate(mongoDbFactory(mongoClient));
	}

	@Bean
	public MongoDbFactory mongoDbFactory(MongoClient mongoClient) {
		return new SimpleMongoClientDbFactory(mongoClient, "test");
	}

	@Bean(destroyMethod="shutdown")
	public MongoServer mongoServer() {
		MongoServer mongoServer = new MongoServer(new MemoryBackend());
		mongoServer.bind();
		return mongoServer;
	}

	@Bean(destroyMethod="close")
	public MongoClient mongoClient(MongoServer mongoServer) {
		return MongoClients.create("mongodb://" + mongoServer.getLocalAddress().getHostName() + ":" + mongoServer.getLocalAddress().getPort());
	}
}
```

**Comment by bsvenkat22** [comment]
Thank you so much for your response. I was so fixated on new ServerAddress(mongoServer().getLocalAddress()) code that I was trying to see if there is any other class that could recreate this. I didn't know this would create new port every time. I need to understand the code more.
But MongoClients.create("mongodb://" + mongoServer.getLocalAddress().getHostName() + ":" + mongoServer.getLocalAddress().getPort()) solves the problem. Thanks again.
