### ISSUE TITLE
Implementing oplog functionality

### ISSUE THREAD

**Issue by snava10** [bwaldvogel/mongo-java-server#134]
MongoDb when set up as a replica set mantains a collection in the local database called [oplog.rs](https://docs.mongodb.com/manual/core/replica-set-oplog/) where it records a log of all changes that take place (insertions, updates, deletions, etc). Among other things the oplog is used in the implementation of [change streams](https://docs.mongodb.com/manual/changeStreams/).
This issue is to intersect the insertions, updates and deletions and create the corresponding entrances in the oplog.

See [this](https://medium.com/@atharva.inamdar/understanding-mongodb-oplog-249f3996f528) for an overview of the structure of the oplog documents.

**Comment by snava10** [comment]
This pull request #131 implements the insertion.

**Comment by bwaldvogel** [comment]
I’ve added some support for updates and deletes in the oplog: https://github.com/bwaldvogel/mongo-java-server/commit/e686643a8f39f4ca0eb4fb0aaa17dce90f3504a8.

I’ve also just released version `1.28.0`…

**Comment by bwaldvogel** [comment]
What is missing for this issue?

**Comment by snava10** [comment]
I think we can close it.
