### ISSUE TITLE
Cannot get dependency through maven central

### ISSUE THREAD

**Issue by Lorac** [bwaldvogel/mongo-java-server#14]
When I'm trying to import with 

        <dependency>
            <groupId>de.bwaldvogel</groupId>
            <artifactId>mongo-java-server</artifactId>
            <version>1.4.0</version>
            <scope>test</scope>
        </dependency>

Could not find artifact mongo-java-server:mongo-java-server-core:jar:1.4.0 in central (https://repo1.maven.org/maven2)

**Comment by HaVonTe1** [comment]
The mongo-java-server.pom has false groupIds of its own dependencies. This build is broken.

**Comment by bwaldvogel** [comment]
I've release version 1.4.1 that fixes the groupId. Can you re-test as soon as the artifacts are synched to Maven central?

**Comment by bwaldvogel** [comment]
It's synched now.

**Comment by Lorac** [comment]
It's all good thanks!
