### ISSUE TITLE
Range queries with minKey are broken

### ISSUE THREAD

**Issue by advptr** [bwaldvogel/mongo-java-server#140]
We've a range query utilizing minKey and maxKey (for a compound identity). The query worked excellent with 1.24 but since 1.25 it's broken. Since we also would like to have support for UUID (from 1.25) this has become a severe problem. 

The actual query looks like:

  BasicDBObjectBuilder.start()
      .push("_id")
        .push("$gt")
          .add(ID_1, key1)
          .add(ID_2, new MinKey)
          .pop()
        .push("$lt")
          .add(ID_1, key1)
          .add(ID_2, new MaxKey)
        .pop()
      .pop
    .get

Should be as simple as just adding minKey to SORT_ORDER in the class ValueComparator. A fix would be highly appreciated.

**Comment by bwaldvogel** [comment]
The regression should be fixed in faf21d4b7d7a9a3c4274c29dec3327e5757f0f7e

**Comment by bwaldvogel** [comment]
Fixed in version `1.29.0`.
