### ISSUE TITLE
renaming a collection is not possible

### ISSUE THREAD

**Issue by HaVonTe1** [bwaldvogel/mongo-java-server#15]
this.mongoDB.getCollection("test_1434609693762").rename("test", true);

results in:

com.mongodb.CommandFailureException: { "serverUsed" : "localhost:35233" , "errmsg" : "no such cmd: renameCollection" , "bad cmd" : { "renameCollection" : "testdb.test_1434609693762" , "to" : "testdb.test" , "dropTarget" : true} , "code" : 59 , "ok" : 0}
	at com.mongodb.CommandResult.getException(CommandResult.java:76)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:140)
	at com.mongodb.DBCollection.rename(DBCollection.java:1314)
	at com.mongodb.DBCollection.rename(DBCollection.java:1296)

Using:

		<dependency>
			<groupId>org.mongodb</groupId>
			<artifactId>mongo-java-driver</artifactId>
			<version>2.13.0</version>
		</dependency>
		<dependency>
			<groupId>de.bwaldvogel</groupId>
			<artifactId>mongo-java-server</artifactId>
			<version>1.4.1</version>
			<scope>test</scope>
		</dependency>

Any ideas?

**Comment by bwaldvogel** [comment]
It’s not yet implemented. Thanks for reporting.

**Comment by bwaldvogel** [comment]
Could you re-test the issue on bec22d3?

**Comment by bwaldvogel** [comment]
mongo-java-server v1.4.2 is released and contains the fix
