### ISSUE TITLE
java.lang.ClassCastException when switching from 1.28.0 to 1.29.x

### ISSUE THREAD

**Issue by keterp** [bwaldvogel/mongo-java-server#151]
When switching from version 1.28.0 to 1.29.x and following I get the following exception in some test cases that use Mongo Java Server:
java.lang.ClassCastException: Cannot cast org.bson.Document to java.util.List
        at java.lang.Class.cast(Class.java:3369)
        at org.bson.Document.get(Document.java:140)
       ...
We are using jdk 1.8 and mongo-java-driver 3.9.0 

Thanks

**Comment by bwaldvogel** [comment]
Please describe in more detail in which situation (i.e. for which query / which data) this happens

**Comment by keterp** [comment]
**Thanks for the response.
The relevant code sippet is this:**
       ```
 List<Document> resultList = new ArrayList<>();
        List<Bson> queryPipeline = filter.build();
        System.out.println(queryPipeline.toString());
        dataAccess.getDatabase().getCollection(VEHICLE_COLLECTION).aggregate(queryPipeline).forEach( (Consumer<Document>) resultList::add);
        System.out.println(resultList);
```

**The toString of the queryPipeline results into this for the test case in question:**
_[Stage{name='$match', value=Operator Filter{fieldName='releases._id', operator='$in', value=[1002081]}}, Stage{name='$match', value=Operator Filter{fieldName='modelRange._id', operator='$in', value=[26]}}, { "$lookup" : { "from" : "VehicleModelRange", "localField" : "modelRange._id", "foreignField" : "id", "as" : "vehicleModelRangeParams" } }, Stage{name='$match', value=Operator Filter{fieldName='vehicleModelRangeParams.releases._id', operator='$in', value=[1002081]}}, { "$lookup" : { "from" : "VehicleMake", "localField" : "make._id", "foreignField" : "id", "as" : "vehicleMakeParams" } }, Stage{name='$match', value=Operator Filter{fieldName='vehicleMakeParams.releases._id', operator='$in', value=[1002081]}}, Stage{name='$project', value={ "_id" : 1, "id" : 1, "name" : 1, "type" : 1, "lifecycleState" : 1, "approvalState" : 1, "releases._id" : 1, "vehicleMakeParams.bmwGroupMake" : 1, "modelRange._id" : 1, "vehicleModelRangeParams.modelRangeName" : 1, "vehicleModelRangeParams.modelRangeCode" : 1, "make._id" : 1, "make.name" : 1, "series._id" : 1, "series.name" : 1, "modelName" : 1, "okaCode" : 1, "vehicleType" : 1, "fuelType" : 1, "cylinders" : 1, "vehicleModelRangeParams.releases._id" : 1, "vehicleMakeParams.releases._id" : 1 }}]_

**For the mongo-java-server version 1.28.0 the toString of the resultList it this:**
_[Document{{_id=36.0.0, id=36, name=118i [7K31], type=vehicleModel, lifecycleState=new, approvalState=working, modelRange=Document{{_id=26}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=118i, okaCode=7K31, vehicleType=car, fuelType=petrol, cylinders=3}}, Document{{_id=37.0.0, id=37, name=116d [7M71], type=vehicleModel, lifecycleState=new, approvalState=working, modelRange=Document{{_id=26}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=116d, okaCode=7M71, vehicleType=car, fuelType=diesel, cylinders=3}}, Document{{_id=38.0.0, id=38, name=118d [7M91], type=vehicleModel, lifecycleState=new, approvalState=working, modelRange=Document{{_id=26}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=118d, okaCode=7M91, vehicleType=car, fuelType=diesel, cylinders=4}}, Document{{_id=39.0.0, id=39, name=120d xDrive [7N51], type=vehicleModel, lifecycleState=new, approvalState=working, modelRange=Document{{_id=26}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=120d xDrive, okaCode=7N51, vehicleType=car, fuelType=diesel, cylinders=4}}, Document{{_id=40.0.0, id=40, name=120d [7N31], type=vehicleModel, lifecycleState=new, approvalState=working, modelRange=Document{{_id=26}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=120d, okaCode=7N31, vehicleType=car, fuelType=diesel, cylinders=4}}, Document{{_id=41.0.0, id=41, name=M135i xDrive [7L11], type=vehicleModel, lifecycleState=new, approvalState=working, modelRange=Document{{_id=26}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=M135i xDrive, okaCode=7L11, vehicleType=car, fuelType=petrol, cylinders=4}}]_

**and for the version 1.29.0 the result is this:**
_[Document{{_id=36.0.0, id=36, name=118i [7K31], type=vehicleModel, lifecycleState=new, approvalState=working, releases=Document{{_id=[1002081]}}, vehicleMakeParams=Document{{bmwGroupMake=[true], releases=Document{{_id=[1002081]}}}}, modelRange=Document{{_id=26}}, vehicleModelRangeParams=Document{{modelRangeName=[1er Limousine], modelRangeCode=[F40], releases=Document{{_id=[1002081]}}}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=118i, okaCode=7K31, vehicleType=car, fuelType=petrol, cylinders=3}}, Document{{_id=37.0.0, id=37, name=116d [7M71], type=vehicleModel, lifecycleState=new, approvalState=working, releases=Document{{_id=[1002081]}}, vehicleMakeParams=Document{{bmwGroupMake=[true], releases=Document{{_id=[1002081]}}}}, modelRange=Document{{_id=26}}, vehicleModelRangeParams=Document{{modelRangeName=[1er Limousine], modelRangeCode=[F40], releases=Document{{_id=[1002081]}}}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=116d, okaCode=7M71, vehicleType=car, fuelType=diesel, cylinders=3}}, Document{{_id=38.0.0, id=38, name=118d [7M91], type=vehicleModel, lifecycleState=new, approvalState=working, releases=Document{{_id=[1002081]}}, vehicleMakeParams=Document{{bmwGroupMake=[true], releases=Document{{_id=[1002081]}}}}, modelRange=Document{{_id=26}}, vehicleModelRangeParams=Document{{modelRangeName=[1er Limousine], modelRangeCode=[F40], releases=Document{{_id=[1002081]}}}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=118d, okaCode=7M91, vehicleType=car, fuelType=diesel, cylinders=4}}, Document{{_id=39.0.0, id=39, name=120d xDrive [7N51], type=vehicleModel, lifecycleState=new, approvalState=working, releases=Document{{_id=[1002081]}}, vehicleMakeParams=Document{{bmwGroupMake=[true], releases=Document{{_id=[1002081]}}}}, modelRange=Document{{_id=26}}, vehicleModelRangeParams=Document{{modelRangeName=[1er Limousine], modelRangeCode=[F40], releases=Document{{_id=[1002081]}}}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=120d xDrive, okaCode=7N51, vehicleType=car, fuelType=diesel, cylinders=4}}, Document{{_id=40.0.0, id=40, name=120d [7N31], type=vehicleModel, lifecycleState=new, approvalState=working, releases=Document{{_id=[1002081]}}, vehicleMakeParams=Document{{bmwGroupMake=[true], releases=Document{{_id=[1002081]}}}}, modelRange=Document{{_id=26}}, vehicleModelRangeParams=Document{{modelRangeName=[1er Limousine], modelRangeCode=[F40], releases=Document{{_id=[1002081]}}}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=120d, okaCode=7N31, vehicleType=car, fuelType=diesel, cylinders=4}}, Document{{_id=41.0.0, id=41, name=M135i xDrive [7L11], type=vehicleModel, lifecycleState=new, approvalState=working, releases=Document{{_id=[1002081]}}, vehicleMakeParams=Document{{bmwGroupMake=[true], releases=Document{{_id=[1002081]}}}}, modelRange=Document{{_id=26}}, vehicleModelRangeParams=Document{{modelRangeName=[1er Limousine], modelRangeCode=[F40], releases=Document{{_id=[1002081]}}}}, make=Document{{_id=11, name=BMW}}, series=Document{{_id=18, name=1er}}, modelName=M135i xDrive, okaCode=7L11, vehicleType=car, fuelType=petrol, cylinders=4}}]_

As it seems you support new functionality within this version with respect to aggregation, which is great. But the problem seems to be that for e.g. the property vehicleModelRangeParams the value is a bson Document but when we run it against a real mongodb the value is a List of Documents. So when trying to call 
`Document.get("vehicleModelRangeParams", List.class)` it causes a ClassCastException

Thanks

**Comment by bwaldvogel** [comment]
Can you test with the latest version? It’s `1.32.0`.

To reproduce this bug, can you try to create a **minimal** test case?

Example for a small test case:
```java
List<Document> pipeline = jsonList("$match: {$expr: {$or: [{$gt: ['$price', 100]}, {$gt: ['$quality', 70]}]}}");

collection.insertOne(json("_id: 1, price: 10, quality: 50"));
collection.insertOne(json("_id: 2, price: 150, quality: 500"));
collection.insertOne(json("_id: 3, price: 50, quality: 150"));
collection.insertOne(json("_id: 4, price: 10, quality: 5"));

assertThat(collection.aggregate(pipeline))
	.containsExactly(
		json("_id: 2, price: 150, quality: 500"),
		json("_id: 3, price: 50, quality: 150")
	);
```

**Comment by keterp** [comment]
The error appears also with version 1.32.0. I will come up with a test case soon. Thanks

**Comment by bwaldvogel** [comment]
Closing this issue. Please re-open when you are able to provide a (minimal) test cases which reproduces the described issue.
