### ISSUE TITLE
Unrecognized pipeline stage name: '$merge'

### ISSUE THREAD

**Issue by janakbe** [bwaldvogel/mongo-java-server#152]
Does this support aggregate pipeline stage $merge?

**Comment by bwaldvogel** [comment]
It’s not yet implemented. I’m happy to receive a PR. See https://github.com/bwaldvogel/mongo-java-server/commit/0367cc171d3bca4deba8a0dbca0c3a22e564ef5b for the place to add support for the `$merge` stage.

**Comment by bwaldvogel** [comment]
It’s available now in version `1.43.0`.
