### ISSUE TITLE
The $slice option for $push does not support negative values

### ISSUE THREAD

**Issue by Tbk240** [bwaldvogel/mongo-java-server#166]
When trying to test the $slice option for a $push with a negative value, I just get errors. It works with positive values. In the below example, I should end up with a document that contains only the last item added. Instead I get this - "com.mongodb.MongoCommandException: Command failed with error -1: 'Unknown error: fromIndex(0)> to index (-1)..."

Example:
`$push: { 
     "items" : {
          $each: [
               { 
                    "value" : 1,
                    "display": "Test 1"
               },
               { 
                    "value" : 2,
                    "display": "Test 2"
               }
           ],
           $slice: -1
     }
}`

**Comment by bwaldvogel** [comment]
Thanks for the report. Negative `$slice` values are now supported with 2d81eccbd08093e6c90a9498e229e2ab45e75b61.

**Comment by bwaldvogel** [comment]
Available in version `1.37.0`
