### ISSUE TITLE
Problem deleting index (if two indexes exist with the same key attribute)

### ISSUE THREAD

**Issue by YukiInu** [bwaldvogel/mongo-java-server#171]
When there exists two indexes with the same key the index can't be deleted because the query is executed on the collection with all indexes of the database.

de.bwaldvogel.mongo.backend.AbstractMongoDatabase: 450

I inserted one line of code to fix it. Not sure if this is the way to do it or there is a better one:
indexQuery.append("ns", databaseName+"."+ (String) query.get("dropIndexes"));

Not only the key but also the collection name is considered now.

**Comment by bwaldvogel** [comment]
Thanks for the bug report and the suggested fix.
I’ve basically applied your suggestion in 41e40b3915d170a0f213d0e7665c0277857390e1.

**Comment by YukiInu** [comment]
Thank you very much!

**Comment by bwaldvogel** [comment]
Fix is available in version 1.37.0
