### ISSUE TITLE
Unrecognized expression '$toDouble'

### ISSUE THREAD

**Issue by maaw** [bwaldvogel/mongo-java-server#172]
Hi, first thanks for all your work. I'm getting 
`de.bwaldvogel.mongo.exception.MongoServerError: [Error 168] Unrecognized expression '$toDouble'`
using the latest version (1.36 as of today). I'm guessing the expression is not supported by the server.
Can it be added? 
Thanks in advance

**Comment by bwaldvogel** [comment]
It should be straight-forward to add. I’m happy to receive a PR.

**Comment by mattwho76** [comment]
This looks like it would be related to implementing $convert so related to issue 141.

**Comment by bwaldvogel** [comment]
`$toDate` is available in version `1.37.0`
