### ISSUE TITLE
Bug when opening change stream with filter matching documents on two diferent collections

### ISSUE THREAD

**Issue by snava10** [bwaldvogel/mongo-java-server#179]
Due to an error in the oplog implementation, a change stream opened against a collection would pick up documents from another collection if they match the filter.
The solution is to filter documents from the oplog based on their namespace "<dbName>.<collectionName>"
In this way preventing change streams to pick up documents from collections other than the one being watch.

**Comment by bwaldvogel** [comment]
Thanks for your contribution!
