### ISSUE TITLE
Support mongo driver 3

### ISSUE THREAD

**Issue by simonmcooper** [bwaldvogel/mongo-java-server#18]
When trying to use the mongo v3 java client with v1.4.1, the following exceptions are thrown (at least in our local tests):

> ERROR de.bwaldvogel.mongo.wire.MongoWireProtocolHandler - unknown command: MongoQuery(header: MessageHeader(request: 3, responseTo: 0), collection: admin.$cmd, query: { "getlasterror" : 1}, returnFieldSelector: null)
> de.bwaldvogel.mongo.exception.NoSuchCommandException: no such cmd: getlasterror
>	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleAdminCommand(AbstractMongoBackend.java:92) ~[mongo-java-server-core-1.4.1.jar:na]

> ERROR de.bwaldvogel.mongo.wire.MongoWireProtocolHandler - unknown command: MongoQuery(header: MessageHeader(request: 8, responseTo: 0), collection: testdb.$cmd, query: { "create" : "basicTest" , "capped" : false}, returnFieldSelector: null)
> de.bwaldvogel.mongo.exception.NoSuchCommandException: no such cmd: create
>	 at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleCommand(AbstractMongoDatabase.java:148) ~[mongo-java-server-core-1.4.1.jar:na]

**Comment by bwaldvogel** [comment]
mongo-java-server v1.4.2 is released and contains the fix

**Comment by simonmcooper** [comment]
Unfortunately, the 'create' command isn't supported:

> 1296 [nioEventLoopGroup-3-3] ERROR de.bwaldvogel.mongo.backend.AbstractMongoDatabase - unknown query: { "create" : "basicTest" , "capped" : false}
> 1300 [nioEventLoopGroup-3-3] ERROR de.bwaldvogel.mongo.wire.MongoWireProtocolHandler - unknown command: MongoQuery(header: MessageHeader(request: 8, responseTo: 0), collection: testdb.$cmd, query: { "create" : "basicTest" , "capped" : false}, returnFieldSelector: null)
> de.bwaldvogel.mongo.exception.NoSuchCommandException: no such cmd: create
>	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleCommand(AbstractMongoDatabase.java:151) ~[mongo-java-server-core-1.4.2.jar:na]
>	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleCommand(AbstractMongoBackend.java:186) ~[mongo-java-server-core-1.4.2.jar:na]

Sent by the createCollection method calls

**Comment by bwaldvogel** [comment]
could you retest on master?

**Comment by simonmcooper** [comment]
Yup, looks good, thanks!
