### ISSUE TITLE
Condition evaluation should only evaluate the matching selection

### ISSUE THREAD

**Issue by thecrazzymouse** [bwaldvogel/mongo-java-server#191]
The evaluation of the condition cases should only be executed for the matching part.

`{ $cond: [ <boolean-expression>, <true-case>, <false-case> ] }`

The true-case should only be evaluated if the boolean expression is true.

An example of the failing operation

`db.myCollection.aggregate([{$project: {"numItems": {$cond : [ {$isArray : "$item"}, {$size: "$item"}, 0]}} }]) `

`uncaught exception: Error: command failed: {
	"ok" : 0,
	"code" : 17124,
	"errmsg" : "The argument to $size must be an array, but was of type: missing"
} with original command request: {
	"aggregate" : "myCollection",
	"pipeline" : [
		{
			"$project" : {
				"numVms" : {
					"$cond" : [
						{
							"$isArray" : "$item"
						},
						{
							"$size" : "$item"
						},
						0
					]
				}
			}
		}
	],
	"cursor" : {		
	}
} `

**Comment by thecrazzymouse** [comment]
Expression in https://github.com/bwaldvogel/mongo-java-server/blob/d44ca92b208def9e74f103d7e59bf17e388fff18/core/src/main/java/de/bwaldvogel/mongo/backend/aggregation/Expression.java always evaluates the then and else branches on line 302 to 312

**Comment by bwaldvogel** [comment]
Thanks for the bug report. It should be fixed in version `1.39.0`.
