### ISSUE TITLE
Bug: Querying by document with nested byte array doesn't work

### ISSUE THREAD

**Issue by Pinioo** [bwaldvogel/mongo-java-server#197]
The problem happens when one tries to query using a nested document

**Steps to reproduce** (via mongo CLI client):
```
db.Collection.insertOne({ "_id": { "value" : BinData(0,"wSU=") }})
db.Collection.find({ "_id": { "value" : BinData(0,"wSU=") }})
```

**Desired behavior:**
The previously inserted document is found

**Actual behavior:** 
Nothing is found

**Cause:** 
`de.bwaldvogel.mongo.bson.Document#equals` method executes `documentAsMap.equals(o)`, which compares values inside the map using their implementation of `equals` and it fails for `byte[]`

**Comment by bwaldvogel** [comment]
Thanks, this should be fixed in version `1.41.0`.
