### ISSUE TITLE
'$pull' does not work well

### ISSUE THREAD

**Issue by zhuzhenguang** [bwaldvogel/mongo-java-server#20]
Hello:
I write a test case to execute a 'pull' operation using your stub mongo, but it dose not worked. My code as followed.
        
     BasicDBObject obj = json("_id: 1");
     collection.insert(obj);
     collection.update(obj, json("$set: {field: [{'key1': 'value1', 'key2': 'value2'}]}"));
     collection.update(obj, json("$pull: {field: {'key1': 'value1'}}"));

The 'field' should be empty after 'pull', but it exist yet. And if I use 

    $pull: {field: {'key1': 'value1', 'key2': 'value2'}}

it could work well. However, I think the relation of match conditions of 'pull' is 'OR' but not 'AND'.
Could you help me to resolve it ? Thanks a lot.

**Comment by bwaldvogel** [comment]
Thanks for reporting. Could you retest on current master?

**Comment by zhuzhenguang** [comment]
Thanks, current master is OK. When upload it to maven center?

**Comment by bwaldvogel** [comment]
Done. Version 1.4.4 contains the fix.
