### ISSUE TITLE
$sample stage support

### ISSUE THREAD

**Issue by sradyushkin** [bwaldvogel/mongo-java-server#202]
Is there $sample aggregation stage support? When I try to use it I receive error like this: Command failed with error 40324 (Location40324): 'Unrecognized pipeline stage name: '$sample'' on server localhost:45617

**Comment by agarwali** [comment]
I have a use case for this as well. I am happy to contribute. Is it simply adding another aggregation stage?

**Comment by bwaldvogel** [comment]
Available in version `1.42.0`.
