### ISSUE TITLE
Use of undefined variable: NOW

### ISSUE THREAD

**Issue by saawancn** [bwaldvogel/mongo-java-server#207]
[{"$err" : "Use of undefined variable: NOW", "errmsg" : "Use of undefined variable: NOW", "code" : 17276, 
I am using $$NOW operator in the aggregation pipeline

**Comment by bwaldvogel** [comment]
`$$NOW` is not yet implemented but it shouldn’t be too hard to do so. Are you happy to contribute to this project and submit a PR?

**Comment by bwaldvogel** [comment]
It’s available now in version `1.43.0`.
