### ISSUE TITLE
PostgreSQL backend

### ISSUE THREAD

**Issue by ArturFormella** [bwaldvogel/mongo-java-server#22]
Hello!
I was thinking about PostgreSQL backed - with JSONB, json_agg and other PG build-in features to expose tables as collections.

Could you help me with architecture? 
What is the best place to start? 

My first approach:
- .createCollection()	= CREATE TABLE name (id serial, data JSONB) 
- .find() 			= SELECT jsonb_agg( ROW_TO_JSON(*) ) WHERE ???
- .insert([a,b,c])		= INSERT INTO name (data) VALUES (a),(b),(c)

**Comment by bwaldvogel** [comment]
Very nice idea.

I’ve started a new branch: [postgres-backend](https://github.com/bwaldvogel/mongo-java-server/tree/postgres-backend)

Most of the implementation will go to `de.bwaldvogel.mongo.backend.postgres.PostgresCollection`.
My initial version is just a starting point with many rough edges.
For testing, you can use `PostgresBackendTest`. It assumes a locally running Postgres database with credentials as you can see in the test.

An interesting question will be how to serialize/deserialize the BSON documents to Postgres compatible JSON. At the moment I’m using Jackson. See `de.bwaldvogel.mongo.backend.postgres.PostgresCollection#serializeToJson`.

**Comment by bwaldvogel** [comment]
available in version 1.7.0
