### ISSUE TITLE
serverStatus command behaviour changed after 1.41.0

### ISSUE THREAD

**Issue by elangoravi** [bwaldvogel/mongo-java-server#222]
The command serverStatus() should return a success response despite running from a non-admin database. This was the behaviour until 1.41.0 and breaks in versions after that.

Please review the above scenario and correct me if in case.

**Comment by bwaldvogel** [comment]
Are you willing to submit a pull request?

When you implement a test-case in `AbstractBackendTest.java`, the test framework will run the test against a real MongoDB and the very same test against the mongo-java-server.

The required change is probably pretty similar to what I recently implemented for the `ping` command: https://github.com/bwaldvogel/mongo-java-server/commit/e9394f796a219e38ea710b553cd5b6a02e4cab3b#diff-8a2ceb6962e9f57a349690049177ca4830606986f2e20dcbe32019b98d0037cb

**Comment by elangoravi** [comment]
#223
