### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by JMVM** [bwaldvogel/mongo-java-server#23]
Getting next warning trace when using **mongo-java-sever** as dependency and not using SLF4j.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
```

I think it could be fixed adding **slf4j-simple** as dependency in the server pom.xml.

**Comment by bwaldvogel** [comment]
When you use `mongo-java-server` as library, we explictily do not want to define any kind of logging:
> Note that embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. **When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose**.
http://www.slf4j.org/codes.html#StaticLoggerBinder
