### ISSUE TITLE
Update mongodb-driver from v 5.1.4 to v 5.2.0 fails

### ISSUE THREAD

**Issue by fokko2402** [bwaldvogel/mongo-java-server#233]
When are you planning to update the server (or driver) version?
Building my project with mongodb-driver v 5.2.0 leads to the error "com.mongodb.MongoIncompatibleDriverException: Server at localhost:59444 reports wire version 6, but this version of the driver requires at least 7 (MongoDB 3.6)".
With v 5.1.4 we had no problems, but we want to stay up-to-date with mongodb.

**Comment by raja-hm** [comment]
Is there any plan to fix this issue? with latest spring boot mongo data which has 5.2.1 version mongodb-driver same issue seen.

**Comment by bwaldvogel** [comment]
I just released version `1.46.0` which bumps the wire protocol version to `7`. Please let me know if this works in your case.

**Comment by amazing4u** [comment]
Version 1.46.0 fixed the problem.

Thank you!
