### ISSUE TITLE
 invalid operator: $elemMatch

### ISSUE THREAD

**Issue by lanmarti** [bwaldvogel/mongo-java-server#26]
I'm having an odd issue. I'm using the Vertx MongoDB client and whenever I call a query containing $elemMatch more than once, I get: 
`com.mongodb.MongoCommandException: Command failed with error 10068: 'invalid operator: $elemMatch' on server 127.0.0.1:31623. The full response is { "$err" : "invalid operator: $elemMatch", "errmsg" : "invalid operator: $elemMatch", "code" : 10068, "ok" : 0 }`

or when performing a normal find:
`com.mongodb.MongoQueryException: Query failed with error code 10068 and error message 'invalid operator: $elemMatch' on server 127.0.0.1:1945`

The error does not occur in the production database (running mongo 3.6.2), only when using the mock server.
Example queries:
`{"id":{"$elemMatch":{"$in":["test"]}}}`

As the code seems to be running fine on the real database, I'm thinking that maybe something's going wrong in the mock?

**Comment by bwaldvogel** [comment]
Thanks for reporting.
The `$elemMatch` operator is implemented and available in version 1.8.0.
