### ISSUE TITLE
Error getting aggregate

### ISSUE THREAD

**Issue by vepo** [bwaldvogel/mongo-java-server#28]
Is the command `aggregate` not implemented?

```
com.mongodb.MongoCommandException: Command failed with error 59: 'no such cmd: aggregate' on server localhost:27117. The full response is { "$err" : "no such cmd: aggregate", "errmsg" : "no such cmd: aggregate", "code" : 59, "bad cmd" : { "aggregate" : "devices", "pipeline" : [{ "$match" : { } }, { "$project" : { "_id" : 1 } }, { "$group" : { "_id" : null, "ids" : { "$addToSet" : "$_id" } } }], "cursor" : { } }, "ok" : 0 }
```

**Comment by bwaldvogel** [comment]
`aggregate` is not yet implemented.

**Comment by bwaldvogel** [comment]
@vepo Are you interested in contributing? :smiley:

**Comment by vepo** [comment]
Yes. I had started in my forked repo. I will do It slowly.

**Comment by bwaldvogel** [comment]
I’ve started to work on an initial version of the aggregation pipeline.
It currently supports simple use cases such as matching and grouping with `$sum` (`SumAccumulator`), `$min` (`MinAccumulator`) and `$max` (`MaxAccumulator`) accumulators.

Next steps could be:
* Implement [grouping by non-null keys](https://docs.mongodb.com/manual/reference/operator/aggregation/group/#pipe._S_group)
* Implement other [pipeline stages](https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline/) such as `$project`, `$sort` or `$count`
* Implement other [group accumulator operators](https://docs.mongodb.com/manual/reference/operator/aggregation/group/#accumulator-operator) such as `$avg`, `$first`, `$last` or `$addToSet`

**Comment by vepo** [comment]
Hey @bwaldvogel , I had not time this week, but I will try to implement some of this tasks. We are using your library to test our application. I will send to my team this issue to see if anyone want to implement too! 😃

**Comment by bwaldvogel** [comment]
While `aggregate` is of course not (yet) feature complete, the original query of this issue should be working with ecaf59daaece55d1496a84a46e1224f5fdf05eeb.
I would be glad if you could test it.

**Comment by bwaldvogel** [comment]
Note: I’ve just released version `1.9.5` which contains the current snapshot of implemented stages and expressions.

I’m planning to finish support for `aggregate` with version `2.0.0`.

**Comment by hossomi** [comment]
I've been using version 1.11.1 and noticed many aggregation features work nicely. By "finish support" do you mean implement all aggregation stages, operators and accumulators?
I'm particularly interested in `$objectToArray`. I may have a try implementing it in a fork if you don't mind.

**Comment by bwaldvogel** [comment]
@hossomi: Yes, this issue is still open because not all stages, operators and accumulators are implemented yet.
I’m happy to receive pull requests!

**Comment by bwaldvogel** [comment]
@hossomi; The `$objectToArray` expression is implemented in 0e47402. Wanna give it a try?

**Comment by jonasSchulzAdesso** [comment]
Great job with the aggregation functionality!
We still have one issue there using spring data with mongo template. It adds per default a cursor with batch size to the aggregation. The only way working with your server is to set the explain option to true and add an empty cursor in tests only.
Currently this is a dirty hack on our side and we want to get rid of that.

If you are not planning to implement cursor with batchsizes soon, maybe you could change that line to something like accepting options and overwriting them with an empty cursor:

` if (!cursor.isEmpty()) {
            throw new MongoServerException("Non-empty cursor is not yet implemented");
        }`
(AbstractMongoDatabase - Line 567)


Currently we are catching that exception and redo the call with explain option.

**Comment by bwaldvogel** [comment]
Non-empty cursors are ignored with 795be9552a73f85800712311f1565e7386060a49. Can you retest?

**Comment by jonasSchulzAdesso** [comment]
> Non-empty cursors are ignored with [795be95](https://github.com/bwaldvogel/mongo-java-server/commit/795be9552a73f85800712311f1565e7386060a49). Can you retest?

Retested and it works now, thanks a lot!

**Comment by bwaldvogel** [comment]
Version `1.14.0` contains the change.

**Comment by bwaldvogel** [comment]
Version `1.18.0` supports a large set of the aggregate command.
Closing this issue in favor of potential follow-up issues that are more specific.
