### ISSUE TITLE
Unsupported $$ROOT aggregation expression

### ISSUE THREAD

**Issue by bsautel** [bwaldvogel/mongo-java-server#31]
As suggested [here](https://github.com/fakemongo/fongo/issues/316#issuecomment-436440615), I gave a try to `mongo-java-server` to replace fongo which seems to be no longer maintained and does not work with the 3.8 MongoDB Java driver.

First, I would like to thank you @bwaldvogel and all the other contributors for working on this project. Using the wire protocol seems to be a more reliable method as mocking the Java MongoDB driver as Fongo does since each implementation change in the driver can break the tool.

I ran all my tests using `mongo-java-server` and I noticed two blocking issues. I will report the other one in another ticket.

In an aggregation pipeline, I use the grouping operator and the `$$ROOT` expression that references the whole object, unlike `${field}` which references a field of the object. It is documented [here](https://docs.mongodb.com/manual/reference/aggregation-variables/).

I get no error telling that it is unsupported but the field which should contain the result of this expression is `null`.

I tried to use the `${field}` syntax and it seems to be supported. It would probably be necessary to extend this syntax to support the `$$ROOT` expression and maybe the other `$$` specific expressions detailed in the documentation.

**Comment by bwaldvogel** [comment]
Thanks for reporting this issue!
It should be fixed in version `1.9.6`.

**Comment by bsautel** [comment]
It works with the `1.9.6` version.

Thanks for your reactivity! You fixed the three issues I reported so fast!

Thanks to the `1.9.6` release, I could finish the Spring Boot 2.1.0 migration of my application! That's awesome! Congratulations!
