### ISSUE TITLE
$not and $size don't seem to work together

### ISSUE THREAD

**Issue by bsautel** [bwaldvogel/mongo-java-server#32]
As I explained in #31 , I am giving a try to replace fongo with mongo-java-server. Here is the second blocking issue I encounter.

In a request, I am using the `$size` operator combined to the `$not` one on a UUID array field. It matches fields that should not be matched.

Here is the query I execute logged by the driver (I want to match objects in which the `uuidArray` contains a value and other ones (not only this one):

> 12:10:28.839 [main] DEBUG org.mongodb.driver.protocol.command - Sending command '{ "update" : "collection", "ordered" : true, "updates" : [{ "q" : { "$and" : [{ "uuidArray" : { "$binary" : { "base64" : "NETg3mmBuifOvuvTONgxhg==", "subType" : "03" } } }, { "uuidArray" : { "$not" : { "$size" : 1 } } }] }, "u" : { "$pull" : { "uuidArray" : { "$binary" : { "base64" : "NETg3mmBuifOvuvTONgxhg==", "subType" : "03" } } } }, "multi" : true }] }' with request id 42 to database test on connection [connectionId{localValue:6}] to server localhost:38239

The log file contains multiple errors with the #30 error message because I am using UUID types, this may hide some log message that could help me to know more about what happens internally.

I noticed if I remove the `$not` operator, the `$size` one seems to behave as expected. (I tried to match arrays containing a value and whose size is two and it works, but in my use case I can have arrays of any size and, as far as I know, I need the `$not` operator to describe what I want).

**Comment by bwaldvogel** [comment]
Thanks for the report. I can reproduce it.

**Comment by bwaldvogel** [comment]
Fixed in version `1.9.6`. Please let me know if you find other problems.

**Comment by bsautel** [comment]
Thanks for the fix, it works now!
