### ISSUE TITLE
Connect with SSL?

### ISSUE THREAD

**Issue by Steve973** [bwaldvogel/mongo-java-server#46]
Can you provide the option to connect to a MongoServer instance with SSL?

**Comment by bwaldvogel** [comment]
I’ve added `MongoServer.enableSsl(…)` in 8f41f56. Can you check if this works for you?

A fully working example can be found in at [`MongoServerTest.testSsl()`](https://github.com/bwaldvogel/mongo-java-server/blob/8f41f566c835a259a9d18527b7c6b9f052f04f66/test-common/src/main/java/de/bwaldvogel/mongo/MongoServerTest.java#L115).

**Comment by bwaldvogel** [comment]
The new option is available in version `1.13.0`.
