### ISSUE TITLE
Implement ELEM_MATCH query operator

### ISSUE THREAD

**Issue by binout** [bwaldvogel/mongo-java-server#51]
When using filter with **elemMatch**
`
        val filter = elemMatch("materials", eq("materialId", query.materialId))
`

🔥 an exception is thrown 
`
java.lang.IllegalArgumentException: unhandled query operator: ELEM_MATCH
	at de.bwaldvogel.mongo.backend.DefaultQueryMatcher.checkExpressionMatch(DefaultQueryMatcher.java:472)
	at de.bwaldvogel.mongo.backend.DefaultQueryMatcher.checkMatchesValue(DefaultQueryMatcher.java:329)
`

**Comment by binout** [comment]
An example of code to reproduce the issue 
👇
https://github.com/binout/mongo-java-server-elemMatch

**Comment by bwaldvogel** [comment]
Thanks for the bug report. Can you retest on 3f16781?

**Comment by binout** [comment]
👍Yes it works ! Thank you very much 👏

**Comment by bwaldvogel** [comment]
Version `1.13.0` contains the fix.

**Comment by binout** [comment]
Nice ! I was waiting for release 😁
