### ISSUE TITLE
Implement $replaceRoot aggregation stage

### ISSUE THREAD

**Issue by antoniovizuete** [bwaldvogel/mongo-java-server#52]
I'm trying to use $replaceRoot but it seems it's not implemented yet. (version: 1.11.1)

`de.bwaldvogel.mongo.exception.MongoServerError: [Error 40324] Unrecognized pipeline stage name: '$replaceRoot'`

**Comment by antoniovizuete** [comment]
At version 1.12.0 is not implemented yet

**Comment by bwaldvogel** [comment]
Can you give a short and simple test to reproduce this error? Can you double-check that you updated to version `1.12.0`?

**Comment by hossomi** [comment]
`1.12.0` was released at Feb 10th while #49 was merged at Feb 11th.

**Comment by bwaldvogel** [comment]
Oh right :man_facepalming:

**Comment by hossomi** [comment]
Missed by one day!

**Comment by bwaldvogel** [comment]
Available in `1.13.0`

**Comment by antoniovizuete** [comment]
> Available in `1.13.0`

Thanks a lot
