### ISSUE TITLE
Issue with $exists using dot notation

### ISSUE THREAD

**Issue by gthazmatt** [bwaldvogel/mongo-java-server#53]
It seems that any numbers following a dot (as well as any trailing dots) are ignored for $exists queries.

Document doc = new Document("_id", new ObjectId()).append("values", Arrays.asList("A", "B", "C"));
mongoCollection.insertOne(doc);

Document exists = new Document("$exists", true);
Document doc1 = mongoCollection.find(new Document("values", exists)).first();  //exists
Document doc2 = mongoCollection.find(new Document("values.", exists)).first();  //exists
Document doc3 = mongoCollection.find(new Document("values.1", exists)).first();  //exists
Document doc4 = mongoCollection.find(new Document("values.1...", exists)).first();  //exists
Document doc5 = mongoCollection.find(new Document("values.111", exists)).first();  //exists
Document doc6 = mongoCollection.find(new Document("values111", exists)).first();  //null
Document doc7 = mongoCollection.find(new Document("values.....", exists)).first();  //exists
Document doc8 = mongoCollection.find(new Document("values.....111", exists)).first();  //illegal key
Document doc9 = mongoCollection.find(new Document("values.abc", exists)).first();  //null

**Comment by bwaldvogel** [comment]
Thanks for your bug report.

>It seems that any numbers following a dot (as well as any trailing dots) are ignored for $exists queries.

Actually I observe a slightly different behavior with MongoDB 4.0.
I’ve tried to implement that behavior in 7bfbac757b97bc9fcfa3024d72bcf1818b152ca8.

Can you retest?

**Comment by gthazmatt** [comment]
I'm not setup to build the project. Could you package a jar up for me?

**Comment by bwaldvogel** [comment]
It’s quite easy to package the JARs:

```
./gradlew assemble
```

Then you can find the JAR files in the `…/build/libs` directories:
* `core/build/libs/mongo-java-server-core-1.12.0.jar`
* `memory-backend/build/libs/mongo-java-server-memory-backend-1.12.0.jar`

**Comment by gthazmatt** [comment]
My build environment doesn't have access to anything outside the local network. I made an attempt at copying the source code and the gradle jar, but it can't resolve any dependencies.

**Comment by bwaldvogel** [comment]
I’ve published a current `1.13.0-SNAPSHOT` to https://oss.sonatype.org/content/repositories/snapshots/de/bwaldvogel/

Does that work for you?

**Comment by gthazmatt** [comment]
That's perfect. Thanks.

**Comment by gthazmatt** [comment]
That fixed the issue. Thanks for the quick turnaround.

**Comment by bwaldvogel** [comment]
Version `1.13.0` contains the fix.
