### ISSUE TITLE
1.13.0 compatibility with mongo-java-driver and mongo db version

### ISSUE THREAD

**Issue by nkanala** [bwaldvogel/mongo-java-server#55]
When I update the mongo-java-server to 1.13.0 version, I am no longer able to create a mongo connection to mongo db version 3.4 (mongo-java-driver 3.4.3). I see connection timeout errors. Is the 1.13.0 jar compatible with these versions? I have no problems connecting with 1.6.0 version which was being used earlier.

**Comment by bwaldvogel** [comment]
Yes, I’ve actually tested the `ExampleTest` from the README with mongo-java-driver 3.4.3.
