### ISSUE TITLE
Regex Support on _id field

### ISSUE THREAD

**Issue by jonasSchulzAdesso** [bwaldvogel/mongo-java-server#56]
Hello,

we are currently switching from fongo to mongo-java-server for our unit testing. So far it works pretty good, but we have an issue related to a search with IgnoreCase, where we use a regex query like that:

` @Query(value = "{'_id': {$regex : '^?0$', $options: 'i'}}")`
`    UserDocument findByIdIgnoreCase(String userId);`

As a result it always returns null. Is there regex support for the inmemory db?

//update: I analyzed the behaviour and it seems, that regex works on fields, that are not the _id of the document. In case of regex on the _id field it always returns null for me.

**Comment by bwaldvogel** [comment]
Thanks for the bug report.
It should be fixed with 4d9c2b4. Can you retest?

**Comment by jonasSchulzAdesso** [comment]
Retested and works perfectly, thank you!

**Comment by iRodneyS** [comment]
Hi are you going to make a new version with the latest fixes?

**Comment by bwaldvogel** [comment]
Version `1.14.0` contains the fix.
