### ISSUE TITLE
networkless version of the server (or MongoDatabase)

### ISSUE THREAD

**Issue by asereda-gs** [bwaldvogel/mongo-java-server#58]
Hello,

We're using mongo java server for many in-memory tests (with `MemoryBackend`). For each test there is a new TCP connection created and closed which uses unnecessary system resources. 

The reason it is happening for each test is because we prefer `@Rule` over `@ClassRule` to avoid static fields in JUnit.

Are there any plans to create lightweight version of the server (or [MongoDatabase](http://mongodb.github.io/mongo-java-driver/3.8/javadoc/com/mongodb/client/MongoDatabase.html)) without networking ?

Regards.

**Comment by bwaldvogel** [comment]
There are no such plans. The focus of this project is to provide a Java implementation that speaks the wire protocol.

What’s the problem with having a `@ClassRule`?

**Comment by asereda-gs** [comment]
> The focus of this project is to provide a Java implementation that speaks the wire protocol.

This requirement is not contradictory to the original aim of the project. You can still have network layer on the top of existing "backend". Sometimes it is easier to use lightweight / embedded version of the product without connection protocol (eg. [h2](http://www.h2database.com)).
 
> What’s the problem with having a @ClassRule?

That means you have to have static variable and manually manage the state (eg. drop database before/after test).

**Comment by bwaldvogel** [comment]
> This requirement is not contradictory to the original aim of the project. You can still have network layer on the top of existing "backend".

Feel free to submit a PR if you have an idea how to achieve it.

**Comment by asereda-gs** [comment]
Is it acceptable if `core` module depends on mongo java driver ?

**Comment by bwaldvogel** [comment]
Unfortunately it’s not an option. Users of `mongo-java-server` would get a transitive dependency on `mongo-java-driver` in probably a different version.

**Comment by markbigler** [comment]
> Is it acceptable if `core` module depends on mongo java driver ?

I'm not sure if this is a good idea. Once you have a dependency on the `mongo java driver`, you will run into the same problems as `Fongo` (https://github.com/fakemongo/fongo/). You may have to make adjustments for each new version of `mongo java driver` and support the old versions as well.

- https://github.com/fakemongo/fongo/issues/357
- https://github.com/fakemongo/fongo/issues/337
- https://github.com/fakemongo/fongo/issues/367
- many more

I think that for this reason `Fongo` is no longer maintained and many people use `mongo-java-server` instead.

**Comment by asereda-gs** [comment]
Yes, that's a valid point.
