### ISSUE TITLE
_id field should be modifiable during upserts

### ISSUE THREAD

**Issue by bfink13** [bwaldvogel/mongo-java-server#62]
During an update, `AbstractMongoCollection` will throw an exception if the `_id` field is being set. However, if the update is actually an upsert, the `_id` field should be allowed to be set via the update query.

Documentation for specifically `$setOnInsert`: https://jira.mongodb.org/browse/SERVER-9958

**Comment by bwaldvogel** [comment]
I’ve just released version `1.15.0` which contains this fix.
