### ISSUE TITLE
Unrecognized expression '$max'

### ISSUE THREAD

**Issue by ptitcoutu** [bwaldvogel/mongo-java-server#68]
I tried to use mongo-java-server on my project but I had the following error : Unrecognized expression '$max'

the code try to execute an aggregate with a projection of the $max of an array type field.

**Comment by bwaldvogel** [comment]
Can you provide a minimized test case to reproduce it?

**Comment by bwaldvogel** [comment]
I found and fixed (30cce24) cases where `$min`/`$max` did not accumulate the correct value.

Could you provide a test case where you see the "Unrecognized expression '$max'" error?

**Comment by bwaldvogel** [comment]
Version `1.17.0` contains the fix.
