### ISSUE TITLE
distinct on an array not properly working

### ISSUE THREAD

**Issue by freakbite** [bwaldvogel/mongo-java-server#70]
Running distinct on a field in a Document returns all fields in an array.

Running distinct on arrayField in the following example:
[{ document: A, arrayField: [a, b, c] }, { document: B, arrayField: [c, d, e]}]

Expected value: [a,b,c,d,e]
Actual value: [[a,b,c], [c,d,e]]

**Comment by bwaldvogel** [comment]
Thanks for reporting this issue.

It should be fixed with 7449324. Can you retest?

**Comment by bwaldvogel** [comment]
Version `1.17.0` contains the fix.
