### ISSUE TITLE
Support for Change Streams

### ISSUE THREAD

**Issue by asereda-gs** [bwaldvogel/mongo-java-server#72]
Since 3.6 MongoDB supports [change streams](https://docs.mongodb.com/manual/changeStreams/).

It would be great if same functionality can be emulated by mongo-java-server

PS. Thanks for this nice library.

**Comment by snava10** [comment]
I have some time available to work on this, @bwaldvogel please let me know if you would like to include it in the library.

**Comment by bwaldvogel** [comment]
Absolutely, I would be happy to merge a pull request.

**Comment by snava10** [comment]
@bwaldvogel could you plese have a look at this pull request #126 
My plan is to implement change streams as cursor on the oplog collection. This first pull request is implementing a simplified version of cursors for collections in general.

**Comment by bwaldvogel** [comment]
@asereda-gs, @snava10: What is missing for this issue?

**Comment by asereda-gs** [comment]
@bwaldvogel we're testing it internally. @snava10 will have more details
If there are some gaps we'll create additional PR

**Comment by snava10** [comment]
@bwaldvogel  we are just starting to use this feature internally ,I'll report back the  problems if we find any, but as far as this issue goes I think there is nothing else to do.

**Comment by bwaldvogel** [comment]
I’m closing this issue. Please open a new issue for bugs and missing features.
