### ISSUE TITLE
Bulk write upsert index is incorrect

### ISSUE THREAD

**Issue by bfink13** [bwaldvogel/mongo-java-server#73]
Based on the [BulkWriteUpsert documentation](https://mongodb.github.io/mongo-java-driver/3.6/javadoc/com/mongodb/BulkWriteUpsert.html), BulkWriteUpsert.getIndex() should be based on the index of the document in the original bulk write operation. The current implementation in the MemoryBackend sets the index to where the document exists in the returned upserts list.

This assert added to AbstractBackendTest.testBulkUpsert() causes the test to fail:
```
assertThat(result.getUpserts())
    .extracting(BulkWriteUpsert::getIndex)
    .containsExactly(1);
```

**Comment by bfink13** [comment]
Looks like there might also be an issue with nModified - working on that now.

**Comment by bwaldvogel** [comment]
The PR is part of version `1.17.0`.
