### ISSUE TITLE
Commands with non-primary ReadPreference need to be unwrapped

### ISSUE THREAD

**Issue by bfink13** [bwaldvogel/mongo-java-server#78]
When the driver executes a command using a non-primary ReadPreference, it will wrap the query to look like this:
```
{ $query: <the query>, $readPreference: <the ReadPreference> }
```

Since the message is `OP_QUERY` and the collection name ends with `$cmd`, mongo-java-server interprets the query as a command and expects the command type (`find`, `insert`, `update`, etc.) to exist as the first key in the query Document.

When the non-primary ReadPreference scenario occurs (when the `$query` key is present), `MongoDatabaseHandler` should extract the `$query` Document from the query object rather than passing the query object directly.

An example:
```
// this fails:
final MongoClient mongoClient = new MongoClient(new ServerAddress(mongoServer.getLocalAddress()), MongoClientOptions.builder().readPreference(ReadPreference.nearest()).build());
mongoClient.getDatabase("testdb").getCollection("coll").countDocuments();


// this succeeds:
final MongoClient mongoClient = new MongoClient(new ServerAddress(mongoServer.getLocalAddress()), MongoClientOptions.builder().readPreference(ReadPreference.primary()).build());
mongoClient.getDatabase("testdb").getCollection("coll").countDocuments();
```

This was tested with mongo-java-driver 3.10.1. I believe this covers the issues brought up in #66 and #77.

**Comment by bwaldvogel** [comment]
Version `1.17.0` contains the fix.
