### ISSUE TITLE
Support for positional-all operator

### ISSUE THREAD

**Issue by waynerijsdijk** [bwaldvogel/mongo-java-server#82]
Since 3.6 MongoDB supports the [positional-all](https://docs.mongodb.com/manual/reference/operator/update/positional-all/) operator.

The [filtered positional operator](https://github.com/bwaldvogel/mongo-java-server/issues/60) has been added to this library a few months ago. It would be awesome if the positional-all could be supported aswell.

**Comment by bwaldvogel** [comment]
I added support in 3baa7af0. Can you re-test it?

**Comment by waynerijsdijk** [comment]
Thanks for the fast response. My tests are working as expected now. Thanks for this awesome test tool.

**Comment by bwaldvogel** [comment]
The fix is part of version `1.18.0`.
