### ISSUE TITLE
Add existing documents on collection to new index

### ISSUE THREAD

**Issue by cocobey73** [bwaldvogel/mongo-java-server#83]
When I create an index on a collection that already has data, the existing documents are not added to this new index. 

This leads to inconsistent results from find operations, depending if the index is use or not. 

I wonder if after creating a new index, the existing documents should be added to it.

**Comment by bwaldvogel** [comment]
Thanks for reporting.
Can you re-test on 34827cf10c047e8eabd8a69ab5ac5ae8217c3354?

**Comment by bwaldvogel** [comment]
The fix is part of version `1.18.0`.

**Comment by cocobey73** [comment]
Thanks
