### ISSUE TITLE
Conflicting updates - Updating the path 'x.y' would create a conflict at x'

### ISSUE THREAD

**Issue by aidanwhiteley** [bwaldvogel/mongo-java-server#85]
Hi - great project - thanks!

With the release of 1.18.1, the following Spring MongoTemplate based code has started throwing exceptions as follows

        UpdateResult updateResult = mongoTemplate.updateFirst(
                Query.query(Criteria.where("id").is(bookId).and("comments.id").is(commentId)),
                new Update().set("comments.$.commentText", "").set("comments.$.deleted", true).set("comments.$.deletedBy", removerName),
                Book.class);

org.springframework.dao.DataIntegrityViolationException: Updating the path 'comments.$.deletedBy' would create a conflict at 'comments.$'; nested exception is com.mongodb.MongoWriteException: Updating the path 'comments.$.deletedBy' would create a conflict at 'comments.$'

The above code continues to work without throwing exceptions on
a) code prior to 1.18.1 (i.e. 1.18.0 and earlier)
b) against a real Mongo implementation

I see that the commit at https://github.com/bwaldvogel/mongo-java-server/commit/4b8f1d5f3e6698485b22ab7c5ddaca6137678506 looks to be in the same area.

I'm no Mongo expert so happy to be told its my poor code but thought I'd log an issue in case others report similar problems.

Thanks again

Aidan Whiteley

**Comment by bwaldvogel** [comment]
Thanks for reporting this issue. Version `1.18.2` should fix it.
