### ISSUE TITLE
Array filters is not working as expected

### ISSUE THREAD

**Issue by phani113** [bwaldvogel/mongo-java-server#86]
Hi ,

I am getting following exception while using update with array filter.  Same query is working in actual Mongo server.

com.mongodb.MongoCommandException: Command failed with error 9: 'Error parsing array filter :: caused by :: Expected a single top-level field name, found 'charge.maxAge' and 'charge.minAge'' on server localhost:27017. The full response is { "$err" : "Error parsing array filter :: caused by :: Expected a single top-level field name, found 'charge.maxAge' and 'charge.minAge'", "errmsg" : "Error parsing array filter :: caused by :: Expected a single top-level field name, found 'charge.maxAge' and 'charge.minAge'", "code" : 9, "codeName" : "FailedToParse", "ok" : 0 }

**UpdateResult updateResult = mongoTemplate.getCollection(PACKAGE).updateOne(query, update, UpdateOptions);**

**Query:** And Filter{filters=[Filter{fieldName='date', value=Fri Sep 06 00:00:00 IST 2019}, Filter{fieldName='products.productId', value=10416498}, Filter{fieldName='products.charges.maxAge', value=1}, Filter{fieldName='products.charges.minAge', value=0}, Filter{fieldName='products.charges.chargeType', value=chn}, Filter{fieldName='propertyId', value=1000963420}]}

**Update Query:** products.$[product].charges.$[charge].amount -> {Double@10623}9.96

**Array Filters:** And Filter{filters=[Filter{fieldName='charge.maxAge', value=1}, Filter{fieldName='charge.minAge', value=0}, Filter{fieldName='charge.chargeType', value=chn}]}
And Filter{filters=[Filter{fieldName='product.productId', value=10416498}]}

Note: I am using bwaldvogel 1.18.2 version. 

Thanks.

**Comment by bwaldvogel** [comment]
Thanks for reporting this issue. Can you re-test on ee5b240b1b9b32dad83ad583ae4c654a88fa8196?

**Comment by bwaldvogel** [comment]
Fixed in version `1.19.0`
