### ISSUE TITLE
Support $strLenCP function in expression

### ISSUE THREAD

**Issue by asereda-gs** [bwaldvogel/mongo-java-server#87]
[$strLenCP](https://docs.mongodb.com/manual/reference/operator/aggregation/strLenCP/#strlencp-aggregation) returns number chars (UTF8 codepoints) in a string field.

currently this function is not supported by mongo java server:
> Query failed with error code 168 and error message 'Unrecognized expression '$strLenCP''

**Comment by bwaldvogel** [comment]
Implemented in 06cefc7

**Comment by asereda-gs** [comment]
Thank you!

**Comment by bwaldvogel** [comment]
Part of version `1.19.0`
