### ISSUE TITLE
H2 Backend doesn’t commit updates to disk

### ISSUE THREAD

**Issue by scj7t4** [bwaldvogel/mongo-java-server#89]
The H2Backend doesn’t seem to persist the results of update operations to disk.

To reproduce:

1. Start A H2 Backend pointing to an MVStore file
2. Insert a document.
3. Update the document (eg change a field’s value)
4. Shutdown H2Backend and start it again
5. Observe the changed value is gone, and reverted to the original inserted document.

It looks like the handleUpdate method in H2Collection is empty?

Thanks for your work on this project, it’s a great help!

**Comment by bwaldvogel** [comment]
Thanks for reporting this issue. Could you retest on 2b85b30?

**Comment by scj7t4** [comment]
Yes, that seems to have fixed it on our end, thanks for the quick fix!

**Comment by bwaldvogel** [comment]
The fix is released in version `1.20.0`.
