### ISSUE TITLE
Wrong document update behavior: cannot set id in ReplaceOne with upsert

### ISSUE THREAD

**Issue by jbeshay** [bwaldvogel/mongo-java-server#93]
According to the documentation of replaceOne (https://docs.mongodb.com/manual/reference/method/db.collection.replaceOne/), it is possible to set the _id field in a replaceOne with upsert=true as long as either:
1. No existing document exists that matched the replace filter
2. The existing document has the same _id as in the new document.

Case (1) fails on `1.19.0` with the following error: `After applying the update, the (immutable) field '_id' was found to have been altered to _id: 5d81593cd1a149606e56930f"` although the collection is empty.

This is somewhat similar to the issue in #62 but not exactly the same.

The issue is probably due to using Utils.nullAwareEquals() here:
https://github.com/bwaldvogel/mongo-java-server/blob/master/core/src/main/java/de/bwaldvogel/mongo/backend/AbstractMongoCollection.java#L196

If oldId=null, this error should not be thrown.

**Comment by bwaldvogel** [comment]
The fix is part of version `1.21.0`.
