### ISSUE TITLE
Multikey indexes on array fields that contain nested objects

### ISSUE THREAD

**Issue by icager** [bwaldvogel/mongo-java-server#98]
Hi,

According to the Mongo docs (https://docs.mongodb.com/v3.0/core/index-multikey/#index-arrays-with-embedded-documents) it should be possible to create a multikey index on fields _within_ objects _within_ arrays (as long as the fields themselves are not (both) arrays).

This functionality had been working fine in our unit tests until we swapped from Fongo to mongo-java-server. I added the following test to `memory-backend/src/test/java/de/bwaldvogel/mongo/backend/IndexTest.java`:
```
    @Test
    public void testGetKeyValues_multiKey_document_nested_objects() throws Exception {
        Index<?> index = new MemoryUniqueIndex(Arrays.asList(
            new IndexKey("stock.size", true),
            new IndexKey("stock.quantity", true)
        ), false);

        assertThat(index.getKeyValues(
                                new Document("stock", Arrays.asList(
                                                new Document("size", "S").append("color", "red").append("quantity", 25),
                                                new Document("size", "S").append("color", "blue").append("quantity", 10),
                                                new Document("size", "M").append("color", "blue").append("quantity", 50)
                                        )
                        )))
            .containsExactly(
                new KeyValue("S", 25.0),
                new KeyValue("S", 10.0),
                new KeyValue("M", 50.0));
    }
```
which fails with:
```
de.bwaldvogel.mongo.exception.CannotIndexParallelArraysError: [Error 171] cannot index parallel arrays [stock.quantity] [stock.size]
	at de.bwaldvogel.mongo.backend.Index.getKeyValues(Index.java:93)
```

This appears to be because `valuesPerKey` in `mongo-java-server/core/src/main/java/de/bwaldvogel/mongo/backend/Index.java` is evaluated as:
```
{stock.size=[S, S, M], stock.quantity=[25.0, 10.0, 50.0]}
```
and so can't distinguish between `{stock.size[], stock.quantity[]}` and `{stock[].size, stock[].quantity}`.

Happy to submit a PR for this if/when I can, but it'd be great if somebody more in the know than me could confirm this is a bug and not me misunderstanding the library!

Thanks.

**Comment by bwaldvogel** [comment]
Thanks for this well written bug report.
I’ve tried to add support in 47e0ae1 which is already part of version `1.21.0` that I just released.

**Comment by icager** [comment]
That seems to have fixed it - sorry it's taken me so long to check. Thanks for getting to it so quickly!
