### ISSUE TITLE
Dropping collection does not remove indexes

### ISSUE THREAD

**Issue by gthazmatt** [bwaldvogel/mongo-java-server#99]
For a large collection, deleteMany(new Document()) is pretty slow, so I'm dropping the collection and recreating the indexes instead. When writing a unit test for this, I discovered that mongo-java-server does not behave the same as MongoDb on a collection drop in that the indexes still exist. From the documentation: "Removes a collection or view from the database. The method also removes any indexes associated with the dropped collection."

https://docs.mongodb.com/manual/reference/method/db.collection.drop/

**Comment by bwaldvogel** [comment]
Thanks for reporting this issue.
Can you re-test version 31045c59ddc5c16c204be37bdbbedca820bbca03? 

If it helps, you can build a ["fat" JAR as described in the README](https://github.com/bwaldvogel/mongo-java-server#building-a-fat-jar-that-contains-all-dependencies).

**Comment by gthazmatt** [comment]
So, my build environment doesn't have internet access. We have a clone of maven central, so I thought changing mavenCentral in build.gradle with our repo would work, but it failed to resolve com.github.kt3k.coveralls. Any suggestions?

**Comment by bwaldvogel** [comment]
As a quick workaround you could try to (temporarily) remove the coveralls plugin and its configuration from `build.gradle`. You don’t need it if you just want to package/assemble.

**Comment by gthazmatt** [comment]
It still can't resolve the shadow plugin.

**Comment by bwaldvogel** [comment]
You can re-test on version `1.21.0` which contains the fix.

**Comment by gthazmatt** [comment]
It looks good. Thanks for the help.
